Vault/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Vault.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Vault/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Vault.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }

        public RedirectToPageResult OnPost()
        {
            return new RedirectToPageResult(@"\vault\list");
        }
    }

}

Vault/Pages/Vault/ClientPasswords.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Vault.Pages.Vault
{
    public class ClientPasswordsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Vault/Pages/Vault/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Vault.Core;
using Vault.Data;

namespace Vault.Pages.Vault
{
    public class DeleteModel : PageModel
    {
        private readonly IPasswordData passwordData;
        public Password Password { get; set; }

        public DeleteModel(IPasswordData passwordData)
        {
            this.passwordData = passwordData;
        }


        public IActionResult OnGet(int passwordId)
        {
            Password = passwordData.GetPasswordById(passwordId);

            if (Password == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }

        public IActionResult OnPost(int passwordId)
        {
            var Password = passwordData.GetPasswordById(passwordId);

            if(passwordData != null)
            {
                passwordData.Delete(passwordId);
                passwordData.Commit();
            }

            TempData["Message"] = $"{Password.Name} has been deleted!";
            return RedirectToPage("./List");
        }
    }
}

Vault/Pages/Vault/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Vault.Core;
using Vault.Data;

namespace Vault.Pages.Vault
{
    public class DetailModel : PageModel
    {
        private readonly IPasswordData passwordData;

        public Password Password{ get; set; }

        public DetailModel(IPasswordData passwordData)
        {
            this.passwordData = passwordData;
        }

        public IActionResult OnGet(int passwordId)
        {
            Password = passwordData.GetPasswordById(passwordId);

            if(Password == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }
    }
}

Vault/Pages/Vault/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Vault.Core;
using Vault.Data;

namespace Vault.Pages.Vault
{
    public class EditModel : PageModel
    {
        private readonly IPasswordData passwordData;

        [BindProperty]
        public Password Password { get; set; }

        public EditModel(IPasswordData passwordData)
        {
            this.passwordData = passwordData;
        }

        public IActionResult OnGet(int? passwordId)
        {

            if (passwordId.HasValue)
            {
                Password = passwordData.GetPasswordById(passwordId.Value);
            }else
            {
                Password = new Password();
            }

            if (Password == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }


        public IActionResult OnPost()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if(Password.Id > 0)
            {
                Password = passwordData.Update(Password);
                TempData["Message"] = "Password updated!";
            }
            else
            {
                passwordData.Add(Password);
                TempData["Message"] = "Password created!";
            }

            passwordData.Commit();
            return RedirectToPage("./List");

        }
    }
}

Vault/Pages/Vault/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Vault.Core;
using Vault.Data;

namespace Vault.Pages.Vault
{
    public class ListModel : PageModel
    {
        private readonly IPasswordData passwordData;
        public IEnumerable<Password> passwords { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        [TempData]
        public string Message { get; set; }

        public ListModel(IPasswordData passwordData)
        {
            this.passwordData = passwordData;
        }
        public void OnGet()
        {
            passwords = passwordData.GetPasswordByName(SearchTerm);
        }
    }
}

Vault/Pages/ViewComponents/PasswordCountViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Vault.Data;

namespace Vault.Pages.ViewComponents
{ 
    public class PasswordCountViewComponent : ViewComponent
    {
        private readonly IPasswordData passwordData;

        public PasswordCountViewComponent(IPasswordData passwordData)
        {
            this.passwordData = passwordData;
        }

        public IViewComponentResult Invoke()
        {
            var count = passwordData.GetCountOfPasswords();
            return View(count);
        }
    }
}

Vault/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<p class="h4"> </p>
<br /><br /><br /><br /><br />
<br /><br /><br /><br /><br />
<form method="post">

    <div class="form-group">
        <label for="exampleInputPassword1"><b>Please enter your password to enter the vault.</b></label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary">Enter</button>
</form>

Vault/Pages/Shared/Components/PasswordCount/Default.cshtml
@model int

<div class="Well">
    There are @Model  Passwords. <a asp-page="/Vault/List">See'em all</a>
</div>

Vault/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vault</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Vault</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
   
        <div class="container">
            <vc:password-count></vc:password-count>
            @*&copy; 2019 - Vault - <a asp-area="" asp-page="/Privacy">Privacy</a>*@
        </div>
    </footer>

    @*<environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>*@
    <environment include="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        @*<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>*@



        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Vault/Pages/Vault/ClientPasswords.cshtml
@page
@model Vault.ClientPasswordsModel
@{
    ViewData["Title"] = "";

}

<h2>Client Passwords</h2>

<table class="table" id="passwords"></table>


@section Scripts {
    <environment include="Development">
        <script src="~/node_modules/datatables.net/js/jquery.dataTables.js"></script>
        <link href="~/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" />
        <script src="~/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>
    </environment>

    <script>
        $(function () {
            $.ajax("/api/passwords/",
                { method: "get" })
                .then(function (response) {
                    console.dir(response);
                    $("#passwords").dataTable({
                        data: response,
                        columns: [
                            { "data": "name" },
                            { "data": "passphrase" },
                        ]
                    });
                });
        });
        
    </script>
}

Vault/Pages/Vault/Delete.cshtml
@page "{passwordId:int}"
@model DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Password Page!</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Password.Name ?
</div>

<form method="post">
    <button type="submit" class=" btn btn-danger">Yes</button>
    <a asp-page="List" class="btn btn-default">Cancel</a>
</form>

Vault/Pages/Vault/Detail.cshtml
@page "{passwordId:int}"
@model DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h1 class="h2">Details</h1>

<div>
    Name: @Model.Password.Name
</div>

<div>
    Password: @Model.Password.Passphrase
</div>


<a asp-page="./List" class="btn btn-default">Passwords</a>

Vault/Pages/Vault/Edit.cshtml
@page "{passwordId:int?}"

@model EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Password Page</h1>

<form method="post">
    <input type="hidden" asp-for="Password.Id" />
    <div class="form-group">
        <label asp-for="Password.Name"></label>
        <input asp-for="Password.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Password.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password.Passphrase"></label>
        <input asp-for="Password.Passphrase" class="form-control" />
        <span class="text-danger" asp-validation-for="Password.Passphrase"></span>

    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts{ 
    <partial name="_ValidationScriptsPartial" />
}

Vault/Pages/Vault/List.cshtml
@page
@model ListModel
@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

@if(Model.Message != null)
{
    <div class="alert alert-primary">@Model.Message</div>
}

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>

    </div>
</form>

<partial name="_LinksBasic" model="@Model.passwords" />


<a class="btn btn-primary" asp-page=".\Edit" >Add New</a>

Vault/Pages/Vault/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>The page you are looking for was not found!</h1>
<br />
<br />

<a asp-page=".\List" class="btn btn-primary">Passwords List</a>

Vault/Pages/Vault/_LinksBasic.cshtml
@namespace Vault.Core
@model IEnumerable<Password>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<table class="table">
    @foreach (var password in Model)
    {
        <tr>
            <td>@password.Name</td>
            <td>@password.Passphrase</td>
            <td>
                <a class="btn btn-lg"
                   asp-page=".\Detail" asp-route-passwordId="@password.Id">
                    <i class="glyphicon glyphicon-zoom-in"></i>
                </a>
            </td>
            <td>
                <a class="btn btn-lg"
                   asp-page=".\Edit" asp-route-passwordId="@password.Id">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </td>
            <td>
                <a class="btn btn-lg"
                   asp-page=".\Delete" asp-route-passwordId="@password.Id">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
    }
</table>